import { Geist, Geist_Mono, Quicksand } from "next/font/google";
import "./globals.css";

import Header from "@/components/headers/Header";
import Footer from "@/components/footer/Footer";
import BackToTop from "@/components/BackToTop";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const quickSand = Quicksand({
  variable: "--font-quicksand-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "E-Library",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
          rel="stylesheet"
        />
        <link href="/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" />
      </head>
      <body className={`${quickSand.variable}`}>
        <Header />
        {children}
        <Footer />
        <BackToTop />
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="/lib/easing/easing.min.js"></script>
        <script src="/lib/owlcarousel/owl.carousel.min.js"></script>
      </body>
    </html>
  );
}
